import type { Product } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'hts-6-v14',
    name: 'HTS-6 V14',
    tagline: 'High Torque Spindle — Generation 14',
    description: 'The HTS-6 V14 is the flagship polishing head from COMES Italy, engineered for maximum torque output and superior surface finishing on marble, granite, and engineered stone. Its 14th generation design incorporates advanced sealing technology, reduced vibration, and extended maintenance cycles.',
    image: 'https://comesindia.com/wp-content/uploads/2025/09/2.png',
    gallery: [
      'https://comesindia.com/wp-content/uploads/2025/09/2.png',
      'https://comesindia.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-03-at-9.07.48-AM.jpeg',
      'https://comesindia.com/wp-content/uploads/2026/02/Comes-india-Banners-1920-x-800-px.jpg',
    ],
    category: 'Polishing Head',
    specs: [
      { label: 'Model',        value: 'HTS-6 V14' },
      { label: 'Generation',   value: '14th Gen' },
      { label: 'Head Type',    value: 'High Torque Spindle' },
      { label: 'Motor Power',  value: 'Up to 5.5 kW' },
      { label: 'RPM Range',    value: '200 – 1800 RPM' },
      { label: 'Spindle Count',value: '6' },
      { label: 'Stone Type',   value: 'Marble, Granite, Engineered Stone' },
      { label: 'Origin',       value: 'COMES Italy (Imported)' },
    ],
    features: [
      'Advanced 14th generation sealing technology',
      'Reduced vibration for superior finish quality',
      'Extended maintenance-free operating cycles',
      'Compatible with all standard polishing abrasives',
      'Quick-change spindle system for minimal downtime',
      'Precision-balanced housing for smooth operation',
    ],
    applications: [
      'Marble slab polishing lines',
      'Granite surface finishing',
      'Engineered quartz processing',
      'Calibration and honing operations',
      'Edge polishing and profiling',
    ],
    whatsappMessage: 'Hello COMES India, I am interested in the *HTS-6 V14* polishing head. Please share details, pricing and availability.',
  },
  {
    id: '2',
    slug: 'rg6',
    name: 'RG6',
    tagline: 'Rigid Gear Head — Professional Series',
    description: 'The RG6 delivers consistent polishing performance with a robust rigid gear mechanism. Designed for heavy-duty continuous operation, it excels in high-volume stone processing environments where reliability and consistent pressure distribution are critical.',
    image: 'https://comesindia.com/wp-content/uploads/2025/09/1.png',
    gallery: [
      'https://comesindia.com/wp-content/uploads/2025/09/1.png',
      'https://comesindia.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-03-at-9.07.48-AM.jpeg',
      'https://comesindia.com/wp-content/uploads/2026/02/Comes-india-Banners-1920-x-800-px.jpg',
    ],
    category: 'Polishing Head',
    specs: [
      { label: 'Model',        value: 'RG6' },
      { label: 'Series',       value: 'Professional' },
      { label: 'Head Type',    value: 'Rigid Gear' },
      { label: 'Motor Power',  value: 'Up to 4.5 kW' },
      { label: 'RPM Range',    value: '150 – 1600 RPM' },
      { label: 'Spindle Count',value: '6' },
      { label: 'Stone Type',   value: 'Marble, Limestone, Travertine' },
      { label: 'Origin',       value: 'COMES Italy (Imported)' },
    ],
    features: [
      'Robust rigid gear mechanism for consistent pressure',
      'Heavy-duty design for 24-hour continuous operation',
      'Precision gear alignment for even abrasive wear',
      'High heat-resistance for demanding environments',
      'Modular construction for field-level maintenance',
      'Wide range of compatible abrasive grades',
    ],
    applications: [
      'High-volume marble processing lines',
      'Limestone and travertine polishing',
      'Industrial-scale stone finishing',
      'Multi-head bridge saw integration',
      'Automated production line systems',
    ],
    whatsappMessage: 'Hello COMES India, I am interested in the *RG6* polishing head. Please share details, pricing and availability.',
  },
  {
    id: '3',
    slug: 'storm5-v14',
    name: 'STORM5 V14',
    tagline: 'Storm 5 Spindle — Generation 14',
    description: 'The STORM5 V14 features 5 independently oscillating spindles that adapt to surface variations in real time, delivering unparalleled finish consistency across uneven or textured stone surfaces and setting a new benchmark for premium stone processing.',
    image: 'https://comesindia.com/wp-content/uploads/2025/09/3.png',
    gallery: [
      'https://comesindia.com/wp-content/uploads/2025/09/3.png',
      'https://comesindia.com/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-03-at-9.07.48-AM.jpeg',
      'https://comesindia.com/wp-content/uploads/2026/02/Comes-india-Banners-1920-x-800-px.jpg',
    ],
    category: 'Polishing Head',
    specs: [
      { label: 'Model',        value: 'STORM5 V14' },
      { label: 'Generation',   value: '14th Gen' },
      { label: 'Head Type',    value: 'Independent Oscillating' },
      { label: 'Motor Power',  value: 'Up to 6.0 kW' },
      { label: 'RPM Range',    value: '200 – 2000 RPM' },
      { label: 'Spindle Count',value: '5 (independent)' },
      { label: 'Stone Type',   value: 'All Stone Types' },
      { label: 'Origin',       value: 'COMES Italy (Imported)' },
    ],
    features: [
      '5 independently oscillating spindles',
      'Real-time surface tracking for consistent pressure',
      'Lowest vibration transmission in its class',
      'Ideal for irregular and textured surfaces',
      'Advanced water distribution system',
      'High-gloss mirror finish capability',
    ],
    applications: [
      'Textured and brushed stone surfaces',
      'Natural stone with surface variation',
      'Premium marble with delicate veining',
      'Antique finish production',
      'High-gloss mirror finish processing',
    ],
    whatsappMessage: 'Hello COMES India, I am interested in the *STORM5 V14* polishing head. Please share details, pricing and availability.',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug);
}
